---
name: Publish to TestPyPI
on:
  push:
    branches: [main]
concurrency:
  group: pypi
jobs:
  package-testpypi:
    uses: tektronix/python-package-ci-cd/.github/workflows/_reusable-package-testpypi.yml@v1.4.1
    with:
      package-name: tm_data_types
      repo-name: tektronix/tm_data_types
    permissions:
      contents: read
      id-token: write
      attestations: write
    secrets:
      test-pypi-api-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
